FROM openjdk:11.0.15
ARG SERVER_PORT
ENV SERVER_PORT=$SERVER_PORT
ARG APP_THREAD_COUNT
ENV APP_THREAD_COUNT=$APP_THREAD_COUNT
ARG APP_BOOTSTRAP_SERVERS
ENV APP_BOOTSTRAP_SERVERS=$APP_BOOTSTRAP_SERVERS
ARG APP_BOOTSTRAP_SERVERS_PORT
ENV APP_BOOTSTRAP_SERVERS_PORT=$APP_BOOTSTRAP_SERVERS_PORT
ARG APP_AGENTS_COUNT
ENV APP_AGENTS_COUNT=$APP_AGENTS_COUNT
ARG APP_MESSAGES_COUNT
ENV APP_MESSAGES_COUNT=$APP_MESSAGES_COUNT
ARG APP_KAFKA_TOPIC_NAME
ENV APP_KAFKA_TOPIC_NAME=$APP_KAFKA_TOPIC_NAME

COPY . ./app

WORKDIR ./app
RUN chmod +x gradlew && ./gradlew build
WORKDIR ./build/libs/
ENTRYPOINT ["java", "-jar", "message-generator-0.0.1-SNAPSHOT.jar"]