apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-generator-deployment
  labels:
    app: message-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-generator
  template:
    metadata:
      labels:
        app: message-generator
    spec:
      containers:
        - name: security-demo
          image: CONTAINER_IMAGE
